<a href="https://colab.research.google.com/github/SvitLanaTy/HWDS/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

a = np.array(list(range(1, 11)))

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


## 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
import numpy as np

m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
import numpy as np
m = np.random.randint(1,11,(5,5))
print(m)

[[ 4  3  2  9  1]
 [ 3  6  3  7  1]
 [ 1  6  6  6  6]
 [ 8  8 10  2 10]
 [ 9  1  5  9  3]]


## 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [ ]:
import numpy as np
m = np.random.rand(4,4)
print(m)

[[0.48548933 0.36691355 0.00703387 0.31669195]
 [0.71714657 0.51222946 0.01600414 0.00446534]
 [0.96374874 0.67079683 0.4351257  0.54583958]
 [0.02712163 0.51936086 0.72919357 0.67597273]]


## 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
import numpy as np
a1 = np.random.randint(1,11, 5)
a2 = np.random.randint(1,11, 5)
print("a1:",a1 )
print("a2:",a2 )
print("додавання:",a1+a2)
print("віднімання:",a1-a2)
print("множення:",a1*a2)

a1: [ 5  4  3 10  9]
a2: [3 3 5 9 7]
додавання: [ 8  7  8 19 16]
віднімання: [ 2  1 -2  1  2]
множення: [15 12 15 90 63]


## 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
import numpy as np
v1 = np.random.rand(7)
v2 = np.random.rand(7)
print("Вектор 1:\n",v1 )
print("Вектор 2:\n",v2 )
print("Скалярний добуток:\n",np.dot(v1, v2))

Вектор 1:
 [0.0031696  0.05187626 0.92008014 0.36002799 0.72096498 0.76529054
 0.41175223]
Вектор 2:
 [0.96048372 0.9823031  0.14042042 0.20475208 0.62215256 0.91624817
 0.93005205]
Скалярний добуток:
 1.7896143532612498


## 7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
import numpy as np
m1 = np.random.randint(1,11, (2,2))
m2 = np.random.randint(1,11, (2,3))
print("m1:\n",m1)
print("m2:\n",m2)
print("Результат множення:\n",np.dot(m1,m2))

m1:
 [[4 1]
 [7 5]]
m2:
 [[5 4 6]
 [1 7 1]]
Результат множення:
 [[21 23 25]
 [40 63 47]]


## 8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
import numpy as np
m = np.random.randint(1,11, (3,3))
inverse_m = np.linalg.inv(m)
print("m:\n",m)
print("Обернена матриця:")
print(inverse_m)


m:
 [[ 8  7  6]
 [ 3  9 10]
 [ 2  7  3]]
обернена матриця:
[[ 0.17269076 -0.08433735 -0.06425703]
 [-0.04417671 -0.04819277  0.24899598]
 [-0.01204819  0.1686747  -0.20481928]]


## 9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
import numpy as np

m = np.random.rand(4, 4)
transposed_m = m.T

print("Матриця:\n", m)
print("Транспонована матриця:\n", transposed_m)

Матриця:
 [[0.75326801 0.73402558 0.93819377 0.22367422]
 [0.61368227 0.60526154 0.83450185 0.11509749]
 [0.87889187 0.50066486 0.48328643 0.7765904 ]
 [0.78438551 0.40040731 0.76931055 0.73932844]]
Транмпонована матриця:
 [[0.75326801 0.61368227 0.87889187 0.78438551]
 [0.73402558 0.60526154 0.50066486 0.40040731]
 [0.93819377 0.83450185 0.48328643 0.76931055]
 [0.22367422 0.11509749 0.7765904  0.73932844]]


## 10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=4)

result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Результат множення матриці на вектор:\n", result)

Матриця:
 [[5 2 9 3]
 [7 6 1 4]
 [4 7 8 3]]
Вектор:
 [2 9 5 8]
Результат множення матриці на вектор:
 [ 97 105 135]


## 11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

matrix = np.random.rand(2, 3)

vector = np.random.rand(3)

result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Результат множення матриці на вектор:\n", result)

Матриця:
 [[0.28847827 0.93670234 0.61498604]
 [0.61025882 0.42888627 0.903634  ]]
Вектор:
 [0.03707148 0.23592629 0.37312094]
Результат множення матриці на вектор:
 [0.46115119 0.46097351]


## 12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
import numpy as np

m1 = np.random.randint(1, 11, size=(2, 2))

m2 = np.random.randint(1, 11, size=(2, 2))

result = np.multiply(m1, m2)

print("Матриця 1:\n", m1)
print("Матриця 2:\n", m2)
print("Результат їх поелементного множення:\n", result)

Матриця 1:
 [[3 6]
 [4 7]]
Матриця 2:
 [[8 5]
 [6 8]]
Результат їх поелементного множення:
 [[24 30]
 [24 56]]


## 13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
import numpy as np

m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
result = np.dot(m1, m2)

print("Матриця 1:\n", m1)
print("Матриця 2:\n", m2)
print("Добуток матриць:\n", result)

Матриця 1:
 [[8 8]
 [4 1]]
Матриця 2:
 [[6 5]
 [7 5]]
Добуток матриць:
 [[104  80]
 [ 31  25]]


## 14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
import numpy as np

m = np.random.randint(1, 101, size=(5, 5))
result = np.sum(m)

print("Матриця:\n", m)
print("Сума елементів матриці:\n", result)

Матриця:
 [[ 26  54  40  80 100]
 [ 46  32  30  95  45]
 [ 66  44  80  86  82]
 [ 39  79  74  31  15]
 [ 20  69  97  27  25]]
Сума елементів матриці:
 1382


## 15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
import numpy as np

m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
result = np.subtract(m1, m2)

print("Матриця 1:\n", m1)
print("Матриця 2:\n", m2)
print("Різниця матриць:\n", result)

Матриця 1:
 [[ 1  8 10  6]
 [ 9  3  9  3]
 [ 8  7  7 10]
 [ 3  8  4  7]]
Матриця 2:
 [[ 6  1  5  7]
 [ 8  9  9  7]
 [ 1  5  5  9]
 [ 5  9  8 10]]
Різниця матриць:
 [[-5  7  5 -1]
 [ 1 -6  0 -4]
 [ 7  2  2  1]
 [-2 -1 -4 -3]]


## 16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
import numpy as np

matrix = np.random.rand(3, 3)
sum_matrix_el = np.sum(matrix, axis=1)
vector = sum_matrix_el.reshape(-1,1)

print("Матриця:\n", matrix)
print("Сума елементів кожного рядка матриці:\n", sum_matrix_el)
print("Вектор-стовпчик:\n", vector)

Матриця:
 [[0.8101722  0.71466687 0.19351026]
 [0.73506067 0.71947896 0.17288931]
 [0.97085405 0.81218966 0.34164929]]
Сума елементів кожного рядка матриці:
 [1.71834933 1.62742894 2.124693  ]
Вектор-стовпчик:
 [[1.71834933]
 [1.62742894]
 [2.124693  ]]


## 17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
import numpy as np

m1 = np.random.randint(-10, 11, size=(3, 4))
m2 = np.square(m1)

print("Матриця 1:\n", m1)
print("Матриця 2:\n", m2)


Матриця 1:
 [[ 2  0 -9  5]
 [ 5 -5 -1 -1]
 [ 6 -7  8 -8]]
Матриця 2:
 [[ 4  0 81 25]
 [25 25  1  1]
 [36 49 64 64]]


## 18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
import numpy as np
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)

print("Вектор:\n", vector)
print("Вектор з квадратними коренями попереднього:\n", sqrt_vector)

Вектор:
 [10 16 14 45]
Вектор з квадратними коренями попереднього:
 [3.16227766 4.         3.74165739 6.70820393]
